<a href="https://colab.research.google.com/github/bilalmemon124/Data-Science/blob/main/Lab4_20sw010.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Task 1
import numpy as np

X = np.arange(2, 33, 2).reshape(4, 4)
print(X)


[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [ ]:
#Task 2
import numpy as np

X = np.arange(1, 26).reshape(5, 5)
odd_numbers = X[X % 2 != 0]

print("Original 5x5 ndarray:")
print(X)

print("\nOdd numbers using Boolean indexing:")
print(odd_numbers)


Original 5x5 ndarray:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Odd numbers using Boolean indexing:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [ ]:
#Task 3
import numpy as np

X = np.arange(1, 5)[:, np.newaxis] * np.ones((4, 4))
print(X)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [4]:
#Task 4
import numpy as np

X = np.random.randint(0, 5001, size=(1000, 20))
print(X.shape)

ave_cols = np.mean(X, axis=0)
std_cols = np.std(X, axis=0)

print("Average of values in each column:", ave_cols)
print("Standard Deviation of values in each column:", std_cols)

ave_cols = np.mean(X, axis=0)
std_cols = np.std(X, axis=0)

print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

X_norm = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

ave_X_norm = np.mean(X_norm)
print("Average of all values in X_norm:", ave_X_norm)

ave_min_X_norm = np.mean(np.min(X_norm, axis=0))
print("Average of minimum value in each column of X_norm:", ave_min_X_norm)

ave_max_X_norm = np.mean(np.max(X_norm, axis=0))
print("Average of maximum value in each column of X_norm:", ave_max_X_norm)

permuted_indices = np.random.permutation(5)
row_indices = np.random.permutation(X_norm.shape[0])
X_norm_shuffled = X_norm[row_indices]


num_examples = X_norm.shape[0]
num_train = int(0.7 * num_examples)   # 70% for training
num_crossVal = int(0.15 * num_examples)   # 15% for cross-validation
num_test = num_examples - num_train - num_crossVal   # Remaining 15% for testing


X_train = X_norm_shuffled[:num_train]
X_crossVal = X_norm_shuffled[num_train:num_train + num_crossVal]
X_test = X_norm_shuffled[num_train + num_crossVal:]

print("Shape of X_train:", X_train.shape)
print("Shape of X_crossVal:", X_crossVal.shape)
print("Shape of X_test:", X_test.shape)

(1000, 20)
Average of values in each column: [2491.196 2556.469 2485.83  2438.966 2441.244 2423.933 2517.041 2465.004
 2595.467 2431.867 2462.079 2454.012 2452.953 2487.503 2540.831 2571.125
 2466.434 2540.89  2448.644 2465.089]
Standard Deviation of values in each column: [1453.38843176 1450.94141475 1403.0756377  1445.77977121 1443.19364205
 1458.29523709 1440.72079298 1500.15361013 1446.176493   1430.07899688
 1430.6349544  1490.22752956 1436.3631939  1447.40716455 1426.93053175
 1442.80576149 1437.99863618 1413.82298535 1471.00347153 1473.19600905]
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Average of all values in X_norm: -2.2737367544323207e-17
Average of minimum value in each column of X_norm: -1.7145629445232238
Average of maximum value in each column of X_norm: 1.7345900627907955
Shape of X_train: (700, 20)
Shape of X_crossVal: (150, 20)
Shape of X_test: (150, 20)
